### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by janni2** [sjmeunier/mathlib#1]
Could you maybe point out, what's the goal im comparision to existing solutions like  http://numerics.mathdotnet.com ?

**Comment by sjmeunier** [comment]
This is a very old library of mine, the bulk of which I wrote to learn how to do it. I then started using it in other projects I worked on. My recent refactoring was to clean up the codebase somewhat. So, is there a point to use it in comparison to other alternatives? Maybe not, but then not all projects need to have a point beyond being fun to write.
